import re
from app.channels.base import BaseChannelAdapter
from app.schemas.channels import UnifiedMessage, UnifiedResponse
from app.db.mongo import get_db
from app.core.config import settings
from twilio.rest import Client

def format_whatsapp_markdown(text: str) -> str:
    """
    Converts standard Markdown (generated by LLMs) into WhatsApp's proprietary formatting syntax.
    WhatsApp syntax: *bold*, _italic_, ~strikethrough~, ```code```
    Standard syntax: **bold**, *italic* or _italic_, ~~strikethrough~~
    """
    if not text:
        return ""
        
    # Convert **bold** to *bold*
    text = re.sub(r'\*\*(.*?)\*\*', r'*\1*', text)
    
    # Convert *italic* to _italic_
    text = re.sub(r'(?<!\*)\*(?!\*)(.*?)(?<!\*)\*(?!\*)', r'_\1_', text)
    
    # Convert Markdown Links [text](url) to just the URL (WhatsApp doesn't support hidden links)
    text = re.sub(r'\[(.*?)\]\((.*?)\)', r'\2', text)
    
    # Convert header hashes (### Header) to bold WhatsApp text
    text = re.sub(r'^\s*#{1,6}\s+(.*?)$', r'*\1*', text, flags=re.MULTILINE)
    
    return text

class WhatsAppAdapter(BaseChannelAdapter):
    async def parse_incoming(self, raw_payload: dict) -> list[UnifiedMessage]:
        messages = []
        
        # We need to map the incoming "To" number to the correct company.
        # e.g., 'From': 'whatsapp:+1234567890', 'Body': 'Hello', 'To': 'whatsapp:+0987654321'
        sender = raw_payload.get("From")
        body = raw_payload.get("Body", "")
        to_number = raw_payload.get("To", "").replace("whatsapp:", "")
        
        if not sender:
            return messages
            
        db = await get_db()
        
        # Look up the integration by the "To" number
        tenant_doc = await db["integrations"].find_one({
            "provider": "whatsapp",
            "providerKey": to_number
        })
        
        # Fallback to company 5 if not found for testing purposes as before
        company_id = tenant_doc.get("companyId") if tenant_doc else 5
        website_id = tenant_doc.get("websiteId") if (tenant_doc and tenant_doc.get("websiteId")) else 1
            
        if body:
            messages.append(UnifiedMessage(
                company_id=company_id,
                website_id=website_id,
                channel="whatsapp",
                session_id=sender,
                text=body
            ))
            
        return messages

    async def _get_credentials(self, company_id: int):
        db = await get_db()
        doc = await db["whatsapp_connections"].find_one({"companyId": company_id})
        if doc and doc.get("accountSid") and doc.get("authToken") and doc.get("whatsappNumber"):
            return doc.get("accountSid"), doc.get("authToken"), doc.get("whatsappNumber")
            
        # Fallback to environment variables if DB is empty
        return settings.twilio_account_sid, settings.twilio_auth_token, settings.twilio_whatsapp_number

    async def send_message(self, session_id: str, company_id: int, response: UnifiedResponse) -> bool:
        account_sid, auth_token, from_number = await self._get_credentials(company_id)
        
        if not account_sid or not auth_token:
            print("[WhatsAppAdapter] Missing Twilio credentials.")
            return False
            
        try:
            client = Client(account_sid, auth_token)
            
            client.messages.create(
                from_=f"whatsapp:{from_number}" if not from_number.startswith("whatsapp:") else from_number,
                body=format_whatsapp_markdown(response.text),
                to=session_id
            )
            return True
        except Exception as e:
            print(f"[WhatsAppAdapter] Send error: {e}")
            return False

    async def send_whatsapp_admin_alert(self, ticket_data: dict, company_name: str = "Closira", company_id: int = 5):
        account_sid, auth_token, from_number = await self._get_credentials(company_id)
        
        if not settings.admin_whatsapp_number or not account_sid:
            return False
            
        alert_text = (
            f"🚨 *New Support Ticket Alert* 🚨\n"
            f"*Company:* {company_name}\n"
            f"*Category:* {ticket_data.get('category', 'other').title()}\n"
            f"*Priority:* {ticket_data.get('priority', 'medium').title()}\n"
            f"*Sentiment:* {ticket_data.get('sentimentEmoji', '')} {ticket_data.get('sentiment', 'neutral').title()}\n"
            f"*Customer:* {ticket_data.get('customerName', 'AI Chat User')}\n\n"
            f"*Summary:*\n{ticket_data.get('message', 'No summary provided')}"
        )
        
        try:
            client = Client(account_sid, auth_token)
            client.messages.create(
                from_=f"whatsapp:{from_number}" if not from_number.startswith("whatsapp:") else from_number,
                body=alert_text,
                to=settings.admin_whatsapp_number
            )
            print(f"[WhatsAppAdapter] Admin Alert sent to {settings.admin_whatsapp_number}")
            return True
        except Exception as e:
            print(f"[WhatsAppAdapter] Admin Alert error: {e}")
            return False

whatsapp_adapter = WhatsAppAdapter()
