import asyncio
import httpx

async def main():
    async with httpx.AsyncClient() as client:
        # We need an API key to chat. Let's use the Test Key Direct we created: 85ae026420540141c34e0a1990a0350ec83eb2ed39ffb67dd997070f850950d0
        # Wait, the key hash is stored, we need the raw key? No, the key field in DB is the raw key generated by hashlib.
        # Actually `key` in DB is the hex string. The UI shows the hex string too. Let's just pull it from the DB.
        from app.db.mongo import get_db
        db = await get_db()
        key_doc = await db['api_keys'].find_one({'companyId': 5, 'isActive': True})
        if not key_doc:
            print("No active API key found")
            return
            
        api_key = key_doc['key']
        print(f"Using API Key: {api_key}")
        
        headers = {
            "x-api-key": api_key,
            "Content-Type": "application/json"
        }
        
        body = {
            "query": "The puzzle in the Egypt room was completely broken and we wasted 20 minutes! I want a full refund.",
            "sessionId": "test_api_session_1",
            "customerName": "Test User via API"
        }
        
        print("Sending message to /api/rag/chat...")
        r = await client.post('http://127.0.0.1:5001/api/rag/chat', json=body, headers=headers, timeout=30.0)
        print("Status:", r.status_code)
        print("Response:", r.json())

if __name__ == "__main__":
    asyncio.run(main())
